### ISSUE TITLE
Remarks for Section 1 - Setup

### ISSUE THREAD

**Issue by tshaiman** [kaiohenricunha/aws-scalable-metabase-deployment#171]
#### TLDR; The tutorial is Amazing . thank you . here are some minor issues I've found for Step1 - Setup.

1. ```Finally, cd back to the environments/lab folder and run terraform init```

this outputs the following error : 
```
│ Warning: Reference to undefined provider
│
│   on main.tf line 49, in module "eks_fargate_karpenter":
│   49:     aws.virginia        = aws.virginia
│
│ There is no explicit declaration for local provider name "aws.virginia" in module.eks_fargate_karpenter, so Terraform is assuming you mean to pass a configuration
│ for "hashicorp/aws".
│
│ If you also control the child module, add a required_providers entry named "aws.virginia" with the source address "hashicorp/aws".
│
│ (and one more similar warning elsewhere)
```

2. The Tutorial Assumes you are on EastUS1 - the region is hardcoded into the terraform files .
add a small remark on the readme about this . 
if change of the region is required , then we need to change the hard coded aws.virginia to lets say aws.ohio , right ? 
anyways , this defintion fails ( see remark 1) 

looking forward to work with this !

**Comment by kaiohenricunha** [comment]
Can you try the steps as outlined and the updated README.md? Do you still see this error?

**Comment by tshaiman** [comment]
the remark has nothing to do with readme file , it talks about regions and how to use them.

never mind, I got answers .
(it has nothing to do with the README  - try to read the actual issue next time )
