### ISSUE TITLE
Remarks for Plan Workflow - Terraform template is out of date and cannot be used

### ISSUE THREAD

**Issue by tshaiman** [kaiohenricunha/aws-scalable-metabase-deployment#172]

**Comment by tshaiman** [comment]
when running the "terraform plan" workflow you get an unsupported field message : 

![image](https://github.com/kaiohenricunha/aws-scalable-metabase-deployment/assets/512709/4bffb767-82d8-4585-9edb-d584913e34e2)

**Comment by kaiohenricunha** [comment]
please, try following the new steps outlined in the updated README.md. do you still see the error?

**Comment by tshaiman** [comment]
of Course I see the error , because it has nothing to do with the readme file
The terraform template reference a non-existing field 

the error is Unsupported Argument.

please review the attach image above carefully.

**Comment by kaiohenricunha** [comment]
> of Course I see the error , because it has nothing to do with the readme file The terraform template reference a non-existing field
> 
> the error is Unsupported Argument.
> 
> please review the attach image above carefully.

Well, communication is a two-sided thing. Assuming both sides can communicate well, one can reply better, but your description was not clear!

I'm not sure i made this clear, but this repo is not some production-grade SaaS/PaaS, just a case study...

Anyways, responding to both your issues:
1. The region warning isn't something to worry about, i'd say. I have seen it multiple times and it never affected the desired infra state.
2. I didn't say it has anything to do with the readme file, just tried to make sure you followed the same process I did, which worked :)
3. After a 30 seconds search on google, I found some recent changes that MAY explain this new unexpected behavior:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/UPGRADE-20.0.md?plain=1#L49-L65

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/UPGRADE-20.0.md?plain=1#L82

There have been some changes on how the EKS and Karpenter modules interact:
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2831

 I'll work on a fix as soon as I have time. I think the solution is here, if you want to work on your side:
 https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/karpenter/main.tf

**Comment by kaiohenricunha** [comment]
I was able to go past this "unsupported" error. Gonna check now if functionality remains the same after all is applied, then commit the changes to this repo.

**Comment by tshaiman** [comment]
[celebrate]     Tomer Shaiman reacted to your message:
________________________________

**Comment by tshaiman** [comment]
Oh , Of course i was googling / unblocking myself here . the aim of the issues is to let YOU know the repo is broken , 
I already moved on by using the AWS Blue Prints solution: 
- https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/patterns/karpenter/README.md
- https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/patterns/fargate-serverless

**Comment by kaiohenricunha** [comment]
> Oh , Of course i was googling / unblocking myself here . the aim of the issues is to let YOU know the repo is broken , I already moved on by using the AWS Blue Prints solution:
> 
> * https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/patterns/karpenter/README.md
> * https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/patterns/fargate-serverless

you weren't just trying to let me know :D 

you wanted me to solve your problem in your deadline, but thanks for the heads up anyways!

**Comment by tshaiman** [comment]
nope. there is no deadline and we are not even using this technology. I just want you to know that your sample does not work.
since you dont care anyhow and closed the ticket without fixing , I have nothing else to say .
keep on with the great non-working samples. !

**Comment by kaiohenricunha** [comment]
Thanks! You seem like a happy fulfilled man. Have a nice day and i'll fix it when I can.

**Comment by kaiohenricunha** [comment]
> nope. there is no deadline and we are not even using this technology. I just want you to know that your sample does not work. since you dont care anyhow and closed the ticket without fixing , I have nothing else to say . keep on with the great non-working samples. !

Thanks! You seem like a happy fulfilled man. Have a nice day and i'll fix it when I can.
